export type Product = {
     id: string;
     name: string;
     slug: string;
     description: string | null;
     main_category: string | null;
     mid_category: string | null;
     sub_category: string | null;
     available_stock: number;
     ingredients: string | null;
     instructions: string | null;
     warning: string | null;
     quantity: number | null;
     quantity_unit: string | null;
     manufacturer_id: string | null;
     image_url: string | null;
     media_urls: string[];
     price: number;
     new_arrival: boolean;
     best_seller: boolean;
     discount: boolean;
     discount_amount: number;
     is_active: boolean;
     promoting: boolean;
     promotion_text: string | null;
     display_on_home: boolean;
     created_at: string;
     updated_at: string;
     manufacturer_name?: string | null;
     manufacturer_value?: string | null;
     manufacturer_url?: string | null;
};

export type ProductDraft = Partial<Product> & {
     name: string;
     description: string;
     price: number | string;
     available_stock?: number;
     manufacturer_id?: string | null;
     image_url?: string | null;
     main_category?: string | null;
     mid_category?: string | null;
     sub_category?: string | null;
     quantity_unit?: string | null;
     new_arrival?: boolean;
     best_seller?: boolean;
     discount_amount?: number;
     is_active?: boolean;
     promotion_text?: string | null;
     display_on_home?: boolean;
};
